# Generated by Django 4.1.5 on 2023-01-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        default=None,
                        max_length=255,
                        unique=True,
                        verbose_name="Item Name",
                    ),
                ),
                (
                    "item_verbose",
                    models.CharField(
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Item Verbose Name",
                    ),
                ),
                (
                    "translation",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Translation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Article",
                "db_table": "article",
                "managed": True,
            },
        ),
    ]
